server:
  port: 8092

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: zyndgjqdydbtlt
    password: ae4196ceb61ad383f02f4633fa9edacde74f2a6e7ea51f99546eeda7892eb93c
    url: jdbc:postgresql://ec2-3-233-100-43.compute-1.amazonaws.com:5432/d2nfj1h1aelr4i
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
    #     ddl-auto: create
    database: postgresql
  logging:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

