DELETE FROM public.simulations_steps;
DELETE FROM public.simulations;

insert into public.simulations(simulation_id, identifier, name_simulation, desc_simulation, subject, action_id, status ) values(1,'0101C072021-0','Caso Benitez', 'Esta es una pequeña descripción para el caso Benitez donde se detalla cosas puntuales', 'Derecho Procesal I', 1, 'CREATED' );
insert into public.simulations(simulation_id, identifier, name_simulation, desc_simulation, subject, action_id, status ) values(2,'0102C072021-1','Caso Paredes', 'Esta es una pequeña descripción para el caso Paredes donde se detalla cosas puntuales', 'Derecho Procesal I', 2, 'CREATED' );
insert into public.simulations(simulation_id, identifier, name_simulation, desc_simulation, subject, action_id, status ) values(3,'0103C072021-2','Caso Sarango', 'Esta es una pequeña descripción para el caso Sarango donde se detalla cosas puntuales', 'Derecho Procesal II', 3, 'CREATED' );


insert into public.p_steps(name, help, description) values('Demanda','help 1','La calificación a la dema
insert into public.p_steps(name, help, description) values('Calificacion de la demanda','help 2','La calificación a la demanda es un acto procesal del juez mediante el cual: 1) avoca conocimiento de la causa, 2) la admite a trámite en caso de ser clara y completa, 3) ordena la citación al demandado y, 4) dispone las demás diligencias que se hayan solicitado en el acto de proposición.');
insert into public.p_steps(name, help, description) values('Contestacion de la demanda','help 3','La contestación de la demanda es el acto procesal mediante el cual el demandado alega todas sus excepciones y defensas respecto de una demanda. La contestación de la demanda tiene la misma importancia para el demandado que la demanda para el demandante.');
insert into public.p_steps(name, help, description) values('Calificación de la contestación de la demanda','help 4','La contestación a la demanda y la reconvención constituyen instituciones procesales previstas en el ordenamiento con el fin de ordenarlo, de manera que la controversia surgida pueda ser conocida y resuelta por los jueces.');
insert into public.p_steps(name, help, description) values('Reconvención','help 5','La reconvención, también conocida como demanda reconvencional, es aquella demanda judicial que ejerce el demandado, en el mismo proceso judicial, al momento de contestar la demanda de la que ha sido objeto. Además de pedir la absolución, el demandado introduce nuevas peticiones al tribunal frente a la otra parte.');
insert into public.p_steps(name, help, description) values('Calificación de la reconvención','help 6','La reconvención debe ser calificada como una demanda, de manera que de encontrarla oscura o incompleta debe mandársela a aclarar bajo las prevenciones del Art. 146 del Código Orgánico General de Procesos."');
insert into public.p_steps(name, help, description) values('Audiencia','help 7','En derecho, una audiencia es un procedimiento ante un tribunal u otro órgano de toma de decisiones oficial, como una agencia gubernamental u otro órgano público.​Una audiencia judicial se distingue de un juicio escrito en que por lo general es más corto y, con frecuencia, menos formal.​');
insert into public.p_steps(name, help, description) values('Resolución','help 8','La resolución judicial es el acto procesal proveniente de un tribunal, mediante el cual resuelve las peticiones de las partes, o autoriza u ordena el cumplimiento de determinadas medidas.​');
insert into public.p_steps(name, help, description) values('Apelación','help 9','El recurso de apelación es un medio de impugnación a través del cual se busca que un tribunal de jerarquía mayor solucione conforme a Derecho la resolución del inferior. Dentro del orden jurisdiccional existen diferentes instancias ordenadas de forma jerárquica.');